### ISSUE TITLE
Issue in uploading images / pdf / binary

### ISSUE THREAD

**Issue by maniadel** [francismeynard/lambda-multipart-parser#3]
Hello, 
I am facing issue when I try to upload an image or pdf. 
Please find here may sample: 

**handler.js**
```
'use strict';

const parser = require('lambda-multipart-parser');
const AWS = require('aws-sdk')

module.exports.hello = async event => {

  const result = await parser.parse(event);
  console.log(result.files);

  const { content, filename, contentType } = result.files[0];

  let params = {
    Bucket: "myBucker",
    Key: filename,
    Body:  content,
    ACL: 'public-read',
    ContentType: contentType,
    ContentDisposition: `attachment; filename="${filename}";`  
    
  };

  const s3 = new AWS.S3();
  return s3.upload(params).promise().then( data => {
    console.log('Successfully uploaded data' + data.Location);

    return {
      statusCode: 200,
      body: JSON.stringify({ message: 'File successfully uploaded !', input: data.Location}, null,2)
    };

  }).catch(err => {
    console.log('ERROR MSG: ', err);
    return {
      statusCode: 509,
      body: JSON.stringify({ message: 'Error ' },  null, 2)
    };

  })

};

```

**Serverless**

```

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:*"
      Resource: "arn:aws:s3:::${self:custom.myBucker}/*" 




functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: file/uploader
          method: post
```

You can use postman or this html code : 

```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>

    


    <h2> Multipart upload  </h2>
    
    <form 
        action="https://xxxxxxxxxxx.execute-api.eu-west-1.amazonaws.com/dev/file/uploader" 
        enctype="multipart/form-data" method="post">
      <div>Text field title: <input type="text" name="title" /></div>
      <div>File: <input type="file" name="multipleFiles" multiple="multiple" /></div>
      <input type="submit" value="Upload" />
    </form>

    
</body>
</html>
```
